# Generated by Django 5.2.16 on 2026-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('species', models.CharField(choices=[('human', 'Human'), ('cat', 'Cat'), ('bunny', 'Bunny'), ('rat', 'Rat'), ('monkey', 'Monkey'), ('other', 'Other')], default='human', max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('location', models.CharField(choices=[('EA', 'Earth'), ('PL', 'Pluto'), ('ET', 'Ether'), ('NW', 'Nowhere')], default='EA', max_length=2)),
                ('id_number', models.CharField(max_length=5, unique=True)),
                ('avatar_style', models.CharField(blank=True, max_length=50)),
                ('main_symptom', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
