# Generated by Django 5.2.16 on 2026-07-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('location', 'id_number'), name='unique_patient_id_per_location'),
        ),
    ]
