# Generated by Django 5.2.16 on 2026-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_patient_id_per_location',
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('location', 'id_number'), name='unique_active_patient_id_per_location'),
        ),
    ]
