# Generated by Django 5.2.16 on 2026-07-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_unique_patient_id_per_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(choices=[('EA', 'Earth'), ('PL', 'Pluto'), ('ET', 'Ether'), ('NW', 'Nowhere'), ('XX', 'Unknown')], default='EA', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('cat', 'Cat'), ('bunny', 'Bunny'), ('rat', 'Rat'), ('monkey', 'Monkey'), ('unknown', 'Unknown')], default='human', max_length=20),
        ),
    ]
