# Generated by Django 5.2.16 on 2026-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_location_alter_patient_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pronouns',
            field=models.CharField(choices=[('she/her', 'She/Her'), ('he/him', 'He/Him'), ('they/them', 'They/Them')], default='they/them', max_length=20),
        ),
    ]
