# Generated by Django 5.2.16 on 2026-07-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
    ]
