# Generated by Django 5.2.16 on 2026-08-07 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientrecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='assigned_professional',
            field=models.CharField(blank=True, choices=[('dr_milo', 'Dr. Milo'), ('rn_tam', 'RN Tam')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='indications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='procedures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='record_type',
            field=models.CharField(choices=[('admission', 'Admission'), ('consultation', 'Consultation')], max_length=20),
        ),
    ]
