# Generated by Django 5.2.16 on 2026-08-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientrecord_assigned_professional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='assigned_professional',
            field=models.CharField(blank=True, choices=[('dr_milo', 'Dr. Milo'), ('rn_tam', 'RN. Tam')], max_length=20),
        ),
    ]
